### ISSUE TITLE
The number of input parameters is insufficient in flatten function

### ISSUE THREAD

**Issue by Lin427** [cvnlab/knkutils#3]
I use the example 1 to test the smoothvolumes function.
a = getsamplebrain;
a(rand(size(a))>.9) = NaN;
a2 = smoothvolumes(a,[2.5 2.5 2.5],[5 5 5]);

The following error occurred：
Wrongly using flatten (line 7)
The number of input parameters is insufficient.
Error constructsmoothingfilter (line 37)
     If all (flatten (flt (1,:,)) == 0) && all (flatten (flt (end,::)) == 0) && ...
Error smoothvolumes (line 63)
   Flt = l1unitlength (constructsmoothingfilter (sd, 0.01));

**Comment by kendrickkay** [comment]
try doing
  which flatten -all
to see what flatten.m function you are using.

**Comment by Lin427** [comment]
Thanks, I found that I use the flatten function is matlab comes with. 
Next time, which function to run a problem, I will first look in your file.
