### ISSUE TITLE
About stimulus_apertures

### ISSUE THREAD

**Issue by Edenkut** [cvnlab/knkutils#7]
Hi, I am a beginner at using retinotopy by pRF analysis.

I tried the runretinotopy.m, and it worked well. 
But the pRF method I used requires the stimulus apertures file(.mat or .nii.gz),
Could you give me some guidance on how to get it by using knkutils?

Thank you in advance for your time and answer.

**Comment by kendrickkay** [comment]
Hi - have you checked out the content at http://cvnlab.net/analyzePRF/ ?

**Comment by kendrickkay** [comment]
Is this link http://cvnlab.net/analyzePRF/stimuluspreprocessing.m from that page what you are looking for?

**Comment by Edenkut** [comment]
Ah, yes, this code is what I want to operate. 
Thank you for sharing it.

Cheers.
Eden
